[development]
address = "0.0.0.0"
serial_device = "/dev/ttyUSB0"
serial_baudrate = 115200
transaction_retry_count = 3
packet_timeout_ms = 10
gcp_project_id = 
gcp_region = 
gcp_registry_name = 
gateway_id = 
mqtt_hostname = 
mqtt_trust_store_path = 
mqtt_username = 
mqtt_token_expiry_time_s = 
